name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSBuild
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Replace with your desired .NET version

      - name: Build and test application
        run: |
          dotnet restore
          msbuild /p:Configuration=Release /p:TargetFramework=net48
          dotnet test --no-restore --verbosity normal
